[versions]
agp = "8.10.1"
androidx-activity = "1.10.1"
androidx-fragment = "1.8.0"
androidx-lifecycle = "2.9.0"
androidx-navigation = "2.9.0"
kotlin = "2.2.0"
leakcanary = "2.14"
material = "1.12.0"
robolectric = "4.15.1"
vanniktech-mavenPublish = "0.32.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-mavenPublish" }

# build-logic plugins
lifecycleprops-common = { id = "com.pubiqq.lifecycleprops.buildlogic.common" }
lifecycleprops-library = { id = "com.pubiqq.lifecycleprops.buildlogic.library" }
lifecycleprops-sample = { id = "com.pubiqq.lifecycleprops.buildlogic.sample" }

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
material = { module = "com.google.android.material:material", version.ref = "material" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

# Gradle plugins
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
